config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'customers/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'customers/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'customers/passwords#new', as: 'new_customer_password'
    resources :customers, only: %i[edit update]
  end
  resources :reservationcs
  root 'homes#top'
end

app/models/reservationc.rb
class Reservationc < ApplicationRecord
end

app/controllers/reservationcs_controller.rb
class ReservationcsController < ApplicationController
  before_action :set_reservationc, only: %i[ show edit update destroy ]

  # GET /reservationcs or /reservationcs.json
  def index
    @reservationcs = Reservationc.all
  end

  # GET /reservationcs/1 or /reservationcs/1.json
  def show
  end

  # GET /reservationcs/new
  def new
    @reservationc = Reservationc.new
  end

  # GET /reservationcs/1/edit
  def edit
  end

  # POST /reservationcs or /reservationcs.json
  def create
    @reservationc = Reservationc.new(reservationc_params)

    respond_to do |format|
      if @reservationc.save
        format.html { redirect_to @reservationc, notice: "Reservationc was successfully created." }
        format.json { render :show, status: :created, location: @reservationc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservationc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservationcs/1 or /reservationcs/1.json
  def update
    respond_to do |format|
      if @reservationc.update(reservationc_params)
        format.html { redirect_to @reservationc, notice: "Reservationc was successfully updated." }
        format.json { render :show, status: :ok, location: @reservationc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservationc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservationcs/1 or /reservationcs/1.json
  def destroy
    @reservationc.destroy
    respond_to do |format|
      format.html { redirect_to reservationcs_url, notice: "Reservationc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservationc
      @reservationc = Reservationc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservationc_params
      params.require(:reservationc).permit(:name, :start_time)
    end
end

app/helpers/reservationcs_helper.rb
module ReservationcsHelper
end

app/views/reservationcs/_form.html.erb
<%= form_with model: reservationc, local: true do |f| %>
  <% if reservationc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservationc.errors.count, "error") %> prohibited this reservationc from being saved:</h2>

      <ul>
      <% reservationc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.datetime_field :start_time %>
  </div>

  <div class="actions">
    <%= f.submit '予約' %>
    <%= link_to 'Back', reservationcs_path %>  
  </div>
  
<% end %>

app/views/reservationcs/edit.html.erb
<h1>Editing Reservationc</h1>

<%= render 'form', reservationc: @reservationc %>

<%= link_to 'Show', @reservationc %> |
<%= link_to 'Back', reservationcs_path %>

app/views/reservationcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservationcs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservationcs.each do |reservationc| %>
      <tr>
        <td><%= reservationc.name %></td>
        <td><%= reservationc.start_time %></td>
        <td><%= link_to 'Show', reservationc %></td>
        <td><%= link_to 'Edit', edit_reservationc_path(reservationc) %></td>
        <td><%= link_to 'Destroy', reservationc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= month_calendar events: @reservationcs do |date, reservations| %>
  <%= date %>
  <% reservations.each do |reservation| %>
  <div>
    <%= reservation.start_time.hour %>:<%= reservation.start_time.min %>
    <%= reservation.name %>
  </div>
  <% end %>
<% end %>

<%= link_to 'New Reservationc', new_reservationc_path %>

app/views/reservationcs/new.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-4"></div>
        <h1>新規予約ページ</h1>
    </div>
        <div class="row">
        <div class="col-4"></div>
        <div><%= render 'form', reservationc: @reservationc %></div>
    </div>
</div>

app/views/reservationcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservationc.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @reservationc.start_time %>
</p>

<%= link_to 'Edit', edit_reservationc_path(@reservationc) %> |
<%= link_to 'Back', reservationcs_path %>