config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'customers/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'customers/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'customers/passwords#new', as: 'new_customer_password'
    resources :customers, only: %i[edit update]
  end
  resources :reservationcs
  root 'homes#top'
end

app/views/layouts/_humberger.html.erb
<div>
    <div id="nav-open">
  <span></span>
</div>
<div id="nav-content">
  <div class="hamburger-top"></div>
  <ul class="category">
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationFunction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="menu">
          <% if customer_signed_in? %>
          <li>ようこそ！</li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'font rounded mr-1'%></li>
          <li><%= link_to "topページ", root_path, class: 'font rounded mr-1'%></li>
          <li><%= link_to "予約", new_reservationc_path, class: 'font rounded mr-1'%></li>
          <li><%= link_to "予約一覧", reservationcs_path, class: 'font rounded mr-1'%></li>
          <li><%= render 'layouts/humberger' %></li>
          <% else %>
          <li><%= link_to "topページ", root_path %></li>
        </ul>
        <% end %>
      </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>